export const GET_ERRORS = "GET_ERRORS";
export const LOGIN_LOADING = "LOGIN_LOADING";
export const REGISTER_LOADING = "REGISTER_LOADING";
export const CHANGE_PW_LOADING = "CHANGE_PW_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
